name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build DockerFile
        run: |
          docker build . -f .docker/covid/Dockerfile -t covid-modeling:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          context: .
          file: .docker/covid/Dockerfile
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: andriygav/covid-modeling
          tags: latest