name: Testing Compatibility

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build DockerFile
        run: |
          docker build . -f .docker/covid/Dockerfile -t covid-modeling:latest